### PR TITLE
[Testing][API6] Bridgemud.Client v0.0.2.0 (Firstish Version)

### PR DESCRIPTION
**Pull request by notjuliee**
// New pull request since updating to api6

https://github.com/notjuliee/Bridgemud

Allows you to get a DM on discord every time you get a /tell or your CF pops.

### CODE REVIEW

**Comment by karashiiro** [comment]
Code LGTM @goaaats

**Comment by reiichi001** [comment]
**Purpose**: Plugin does what it says it's going to do
**Functionality**: Plugin does not appear to have any glaring issues that aren't otherwise noted by the dev
**Safety**: Plugin adheres to our plugin guidelines
**Code Review**: Completed by Karashiiro

**Comment by notjuliee** [comment]
:/

**Comment by karashiiro** [comment]
Hey there; I'm a member of the team responsible for reviewing plugin submissions. First off, thanks for taking the time to submit this plugin. We've noticed that you’ve closed your pull request before we were able to merge it, and we’d like to apologize for the amount of time it’s taken so far. Our approval process for new plugins is currently gated on a few key individuals who have been unable to attend to approvals due to real-life circumstances getting in the way. We know that this is a frustrating issue and that it's led to an unreasonable delay to the process, and we're working on fixing it.

Assuming you still are interested in submitting your plugin to the official Dalamud repository, we’d encourage you to re-open your pull request and bear with us while we work through redefining our approval processes and our existing backlog. We are interested in your contribution, and we apologize once more for how long you've had to wait.

**Comment by notjuliee** [comment]
Hi,

Thank you for your comment, I really appreciate it.

I closed this pull request since the version of the plugin here is horrifically out of date at this point, and as of yesterday no longer even works with the latest server version.

I don't know the process for plugin updates while still in approval queue, so instead I will be resubmitting a new version once it's slightly more stable and I can find the time/energy to submit it.

**Pull request closed without merging**
