### PR TITLE
[Testing] Add Better Housing

### PR DESCRIPTION
**Pull request by Sevii77**
Select furniture based on what you see instead of a massive box. Always active for both indoors and outdoors, there's no config menu.

icon

https://github.com/Sevii77/properhousing

### CODE REVIEW

**Comment by goaaats** [comment]
Could you please add to your plugin description:

* What does it actually do
* How do you use it

**Comment by Sevii77** [comment]
Its been done.

**Comment by Sevii77** [comment]
Don't merge yet.

**Comment by Sevii77** [comment]
Fixed some issues and moved to testing, should be ready now.

**Comment by reiichi001** [comment]
@Sevii77 hit me up in Goatplace discord for your purple dev role. (This is Franz)

**Pull request merged**
