### PR TITLE
Add BardMusicPlayerHelper Plugin v1.0 to testing

### PR DESCRIPTION
**Pull request by MoogleTroupe**

### CODE REVIEW

**Comment by AmenneHolelane** [comment]
"automated music player"

"Make sure that your plugin does not directly interact with the game servers in a way that is: 
a) automatic"

**Comment by MoogleTroupe** [comment]
Music control is external to dalamud, this plug-in simply replaces enter ctrl-v enter or hitting macros to sing along

**Comment by ackwell** [comment]
With strong note that I don't make the decisions here, and hence this is just opinion;

Regardless of what performs the actual _automation_ itself, by including part of the ecosystem in dalamud's primary repository, it arguably "blesses" the entire ecosystem. I.E. a user could install this plugin expecting it to work without helpers, and end up installing the rest of the ecosystem - ergo, putting the dalamud plugin repo as the direct contact line.

If this plugin is expressly designed as a helper for a seperate ecosystem, I feel it makes more sense to provide documentation _within_ that ecosystem for how to set this up (i.e. with a custom repository).

**Comment by MoogleTroupe** [comment]
A counter point to that argument, there are existing chat plugins that use external tools to talk in game today in the main dalamud repo.

**Comment by ackwell** [comment]
> A counter point to that argument, there are existing chat plugins that use external tools to talk in game today in the main dalamud repo.

Indeed, though for both the reasons outlined above, and others that have arisen since it's introduction, I would post exactly the same comment for it.

**Comment by Meowchestra** [comment]
Just want to provide my thoughts and counter-arguments before this possibly gets brigaded by new accounts that dislike bard performance players, as already evident by a new account downvoting. Any ensemble group can probably attest to having in-game trolls and public complaining at times.

>**Make sure that your plugin does not directly interact with the game servers in a way that is:**
>_a) automatic, as in polling data or making requests without direct interaction from the user._

I interpret this as things that operate based on a constant need to get or send updated information to the server. Such as addons that may be scanning the marketplace data non-stop instead of updating results when users last checked or retainer price adjusting to undercut periodically. You still have direct input from the user when they start a song, which also has an eventual stopping point. It would also require a moderate amount of effort to add the necessary lyric events to be used for the chat broadcasting.

To my knowledge, chat broadcasting already exists and is being used by a few addons such as XIVChat & MapLinker to send direct chat lines in-game. To a lesser extent, Sonar for hunt relaying and some discord bridges? Singing along at rehearsed theatre / dance musicals and lyrics for in-game concerts is already something being done today through macros and other available support in external utilities. This Helper plugin would exist more-so to reduce the barrier of needing another client &  use of copy/pasting.

Just for reference, there exists repos that house literal cheating addons for the game without being tackled. In my personal opinion, I believe this small quality-of-life addon isn't even in the same realm. RMT bots will still be advertising 24/7. 🤷‍♀️ 

> _b) outside of specification, as in allowing the player to do submit things to the server that would not be possible by normal means._

I interpret this as modifications to the packet data sent upstream such as how players use to obtain illegitimate hair dye colors before it was patched server-side. Sending chat lines shouldn't violate this since you can do so normally.

**Comment by ascclemens** [comment]
> A counter point to that argument, there are existing chat plugins that use external tools to talk in game today in the main dalamud repo.

There is no automation in these chat plugins or the external tools in question.

**Comment by goofy-somebody** [comment]
_This is my opinion and an option that I offer for the developer._

I don't normally respond to these, however in this regard, I believe the automation of this plugin would disqualify it for the main repo.

If it was for me or even for others to use, but does not qualify to be in the main repo, then I would create my own separate repo like others do.

**Comment by MoogleTroupe** [comment]
Moving this to a separate repo per community feedback

**Pull request closed without merging**
