### PR TITLE
[Testing] Distance 0.9.5.0

### PR DESCRIPTION
**Pull request by PunishedPineapple**
New plugin: Distance

Provides one or more widgets that show distance to the target, focus target, etc., and optionally a special widget that shows the distance until aggroing a boss (for supported bosses).

Known issues:
* Missing data for some fights, including ultimates, normal mode Pandaemonium, and all EW trials.  Feel free to contribute if you want!  (See the plugin repo's readme)

Issues/feedback @ Banana Bread in discord.

### CODE REVIEW

**Comment by PunishedPineapple** [comment]
I created a new PR, because the previous one (#2111) was to the api5 branch, and I don't know how to change the target branch without it being a huge mess.

This includes a version bump (0.9.4.0) since that PR was reviewed by Franz and Kara that I had been waiting for the previous PR before pushing:
* Fixed distance widgets not hiding properly when they should for cutscenes, etc.
* Added a note regarding hardware vs. software cursor differences when the mouseover target widget is set to follow the cursor.
* Additional aggro range data included.

As well as the switch to Dalamud API 6 with version 0.9.4.1.

**Comment by PunishedPineapple** [comment]
Updated to version 0.9.5.0 with the following changes from 0.9.4.1:
* Distance widgets are hidden when ClientState reports being in PvP.

**Comment by karashiiro** [comment]
Code LGTM @goaaats

**Comment by reiichi001** [comment]
**Purpose**: Plugin does what it says it's going to do
**Functionality**: Plugin does not appear to have any glaring issues that aren't otherwise noted by the dev
**Safety**: Plugin adheres to our plugin guidelines
**Code Review**: Completed by Karashiiro

**Pull request merged**
