### PR TITLE
Chat 2 v1.15.3

### PR DESCRIPTION
**Pull request by anna-is-cute**
Chat 2 is a complete **replacement** for the in-game chat.

- Unlimited tabs
- More flexible filtering
- RGB chat channel colours
- Screenshot mode to obfuscate names when sharing chat
- Cleaner layout
- Customisable fonts, opacity, and layout

It's pretty good, I think.

### CODE REVIEW

**Comment by karashiiro** [comment]
Code LGTM, can you add an icon, please?

**Comment by anna-is-cute** [comment]
Added an icon.

**Comment by karashiiro** [comment]
@goaaats Final approval?

**Comment by reiichi001** [comment]
As we know this plugin was previously being used/tested by multiple users and we were providing support for it as a special exception, I think it's fair to to say it passes our plugin guidelines and is otherwise ready for merge.

**Pull request merged**
