### PR TITLE
new translate plugin for google/congnitive

### PR DESCRIPTION
**Pull request by Icehunter**
I didn't see the chat translation plugin anymore. This is meant to give a simple autotranslator using either Google or Cognitive Services.

### CODE REVIEW

**Comment by karashiiro** [comment]
Code LGTM @goaaats

**Comment by reiichi001** [comment]
Please adjust for API 6. You can either close/update this PR. We'll then try to get it through plugin approval.

**Comment by Icehunter** [comment]
> Please adjust for API 6. You can either close/update this PR. We'll then try to get it through plugin approval.

Sure thing! Installing VS again now.

**Comment by Icehunter** [comment]
closed in favour of https://github.com/goatcorp/DalamudPlugins/pull/2254

**Pull request closed without merging**
