### PR TITLE
Add Snooper v0.1.0.3 (first release)

### PR DESCRIPTION
**Pull request by Maia-Everett**
Snooper (inspired by the Listener WoW addon) is a Dalamud plugin to help pay attention to individual speakers during large crowded RP events.

Adds a single slash command:

* `/snooper`: Opens a window that displays latest chat messages (say, shout, yell, emote) from your current target.

Repository: https://github.com/Maia-Everett/dalamud-snooper

### CODE REVIEW

**Comment by karashiiro** [comment]
@goaaats Code LGTM

**Comment by reiichi001** [comment]
**Purpose**: Plugin does what it says it's going to do
**Functionality**: Plugin does not appear to have any glaring issues that aren't otherwise noted by the dev
**Safety**: Plugin adheres to our plugin guidelines

**Comment by Maia-Everett** [comment]
Made a small fix: standard emotes initiated by the player character (starting with "You") will now be correctly recorded in the player's log rather than the targeted character's log.

**Comment by reiichi001** [comment]
Please adjust for API 6. You can either close/update this PR. We'll then try to get it through plugin approval.

**Comment by Maia-Everett** [comment]
@reiichi001 

Updated for API 6. Looking forward to approval!

**Comment by reiichi001** [comment]
@Maia-Everett hit me (Franz) up in Goatplace discord for your purple dev role

**Pull request merged**
