### PR TITLE
[Testing] Redirect 1.0 (Initial Commit)

### PR DESCRIPTION
**Pull request by cairthenn**
Main repo: https://github.com/cairthenn/Redirect

This was essentially created in the absence of MOAction after some repeated nagging from a friend. It offers target replacement functionality for any action that supports it (theoretically, I have not combed through every job, thus the testing). The action-switching aspect wasn't included, though I guess it theoretically could be without much effort.

It was written ground up to offer a (hopefully) intuitive UI and be as future-proof and simple as possible.

I understand that by nature, this conflicts with an existing plugin and I'm fine simply keeping it in my own repository if either you or attick have objections.

Please disregard the pluginmaster.json stuff, I be learnin'. 😅

### CODE REVIEW

**Comment by juiposa** [comment]
A strong +1 to this. This is an almost 1-for-1 replacement for MOActions, but has _significantly_ better user experience.

**Comment by karashiiro** [comment]
Code LGTM @goaaats

**Comment by cairthenn** [comment]
Just a small update on the functionality this provides in case combat-related plugins are accepted:

* The core target changing functionality is basically finalized, and I don't tend to allow for the replacement of one action with another as MOAction does
* The primary reason for that is I have updated the plugin to allow actions to queue from macros, which allows the in-game macro system to be used for those sorts of cases, keeping the UI simple
* I also added an option to let you queue sprint instead of having to mash it (this could easily be moved to its own plugin if it's too fringe)

To try to stay within guidelines and alleviate bugs, both macro queueing and sprint queueing were designed to be non-disruptive to normal action flow: they don't change the game's function or force-queue actions, but instead use information about how the Action function works to let the game queue these things itself.

**Comment by attickdoor** [comment]
Two major notes:

1) I'm strongly against the addition of PvP actions. MoAction intentionally excludes them. PvE is not a scarce resource, but PvP is. Giving players any kind of advantage in PvP means that they better stand to rank higher, "earned" on the back of a plugin others aren't using. I'd want to see this functionality removed before okaying.

2) I think this has already been brought up on the repo, but you should change your ground targets to use the new stuff. It looks like you've borrowed old MoAction code, but you should grab the newest stuff from the repo to implement this. It ought to prevent any weird CD resets and the action not going off, which is currently an issue.

Other than those two things, everything looks good. This seems similar to a MoAction Lite that I'm planning on writing eventually. Sprint I can accept becoming queueable. Macros being queueable is...well, it's another way of resolving the same issue the entire rest of the plugin aims to solve. I guess it'll make chat-macroed abilities usable now. That might unleash an unintended plague of rez macros now that they'll be "safe" to use.

**Comment by cairthenn** [comment]
Understood on the PVP stuff -- it's simply a line of UI code that can come out 😄 

For ground target queueing, I'm using the system the game uses to queue actions. I took exactly what it did in the disassembly and rewrote it -- I'm not aware of how MOAction does it internally. I do remember a brief mention in discord that you took an approach that changed a JMP in the action function and the way I'm doing avoids that oddness.

Edit: [This is my messy research on action queueing](https://gist.github.com/cairthenn/21227b53b624c4e5b7f251b77507f57a#file-tryaction_documation-asm-L162)

**Comment by cairthenn** [comment]
I went ahead and merged the PVP changes into my repo, thanks for the feedback!

I also went and looked at MOAction and it does seem like what I'm talking about is what you went with:

https://github.com/attickdoor/MOActionPlugin/blob/0d9ba30f9d6b4b2ead98182d4e136d6613adbbf4/MOAction/MOAction.cs#L149

This is actually what I was talking about above of doing something with queue behavior that is a bit dangerous, because it can cause things to enter the queue that the game doesn't like there, such as items, which will do funny things like go on CD but not actually fire.

My code mirrors the approach of the game, checking the status (0x244 means something is casting, but can be queued), and then the animation timer. If it can use it instantly (status 0, no rolling animation) it will using the other action call, if not it will throw it into the queue!

**Comment by attickdoor** [comment]
Yup, I see what you mean about ground targets. I had entirely forgotten that MoA currently only does things at mouse cursor anyways, so you're likely more comprehensive. Thank you for disabling PvP. It won't truly be gone until some future patch breaks it, or if you squash commits maybe.

I had a thought while in the shower though. Enabling macro queuing effectively allow PvP actions to still function in an unfair way. I'm not really sure if there's a way to approach this other than "sorry but macros have to go". I'm plenty open to discussion though.

**Comment by cairthenn** [comment]
I actually just thought of the same thing myself, and I'm *pretty sure* I can just check if the action is PVP in the hooked function and return early, which should solve the issue entirely. I'm not currently at home to test such a change, so I'll report back in a few hours 😅

**Comment by attickdoor** [comment]
That ought to work? The macro would still be queued, but the only action possible would be the default action. I can see niche edge cases about shoving a bunch of PvP actions into one macro, but somehow I think that isn't a real issue.

**Comment by attickdoor** [comment]
Wait...no, that wouldn't work. If the macro is successfully queued, it's already game over. Then you can have whatever PvP action you like and it'll act like it's queued. So if you're stopping PvP actions in `TryUseAction`, you're already too late.

**Comment by cairthenn** [comment]
Mmm, I think you may be misunderstanding the control flow. Macros hit the command handler line-by-line, which, presuming they contain an action, are individually routed to `TryUseAction` with param `origin = 2`. The entire macro isn't queued at once, and calling the original function with `origin` changed *within the hook* is what lets it queue in the first place, so you can handle it on a per-action basis still.

**Comment by cairthenn** [comment]
As of the latest commit, PVP configuration is removed from the UI as well as forced to conform to vanilla behavior while used within macros 🎉

**Comment by cairthenn** [comment]
I've updated the plugin to make it safer & more reliable while using ground targeted actions. I isolated the functions that create a `Vector3` for a given ground action and check whether you're targeting the UI/it's LOS/out of range/off somewhere in the sky, and switched over to using those instead of the provided ray casting function.

This has the benefit of fixing ground actions in odd arenas like E4S as well!

**Pull request merged**
