### PR TITLE
[Testing] EnemyListHP

### PR DESCRIPTION
**Pull request by Limiana**
A plugin that shows enemy hp % in enemy list. That's all it does.

### CODE REVIEW

**Comment by MidoriKami** [comment]
Does this conflict with things like enemy list debuffs?

**Comment by Limiana** [comment]
Nope, I only render additional elements in ImGui, so no confligts

**Comment by karashiiro** [comment]
Code LGTM, sorry for the delay 🍡

**Comment by philpax** [comment]
Apologies for the delay, you're good to go 🎉

**Pull request merged**
