### PR TITLE
[Testing] CharSyncPlugin 0.1.0.2

### PR DESCRIPTION
**Pull request by rreminy**
New Character Data Synchronization plugin without using native hooks.

Be sure to make backups before testing this plugin. While I tested and made sure the basic functionality works, I cannot cover every case and different configurations we may have. Therefore caution is advised.

This work is based from the original CharacterSync by goat.

### CODE REVIEW

**Comment by rreminy** [comment]
Hold on before merging, found out you can't close the first time window.....

**Comment by goaaats** [comment]
Some things to consider:
* You should add the backup system I added to the original character data sync, if you didn't already
* It's possible that Dalamud loads while the player is already logged in or logging in, even for normal users
* We're testing a fix for winapi hooks right now, if this doesn't turn out to work well

**Comment by rreminy** [comment]
Alright, I fixed the mistake of not being able to close the CharSync Instructions window, and alright, I'll see if I can figure out how to make a backup of the original data as well in case of mistakes. 

The plugin also already take care of the player being already logged in, I setup some handling for it and in addition the functionality is disabled by default to prevent data loss.

**Comment by Limiana** [comment]
Rather than copying files each time you may as well create symlinks and make a plugin help to manage that
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink
just as a suggestion

**Comment by rreminy** [comment]
Backups Implementation added.

I'll take a look at symlinks some other time.

**Comment by rreminy** [comment]
I decided not to do symlinks for now due to compatibility. Earlier versions of Windows apparently doesn't allows you to create symlinks without being an admin user and I don't want to break it for those who're not in an admin account. It still definitely something to consider in the future however.

**Pull request merged**
