### PR TITLE
[Testing] Oh gee, CD

### PR DESCRIPTION
**Pull request by rootdarkarchon**
OGCD assistant providing Text to Speech, (Custom) Sound Effects and unlimited extra bars to visualize and alert you for your OGCDs. Full feature description is on the github page.

Image previews

OGCD Bars
image

OGCD Tracker
image

Abilities Settings
image

OGCD Groups Settings
image

### CODE REVIEW

**Comment by karashiiro** [comment]
Code LGTM @goaaats

**Comment by reiichi001** [comment]
I'm having some difficulty reviewing this plugin. 

The config UI loads up fine, but despite enabling everything in the Astrologian section (my selected class for testing), I don't see anything happening when using this plugin on a test dummy or in instances.

Can you please verify it's working or provide some documentation on how to use/test it? I tried enabling the OGCD tracker that is supposed to not require a group and also put all skills into a group, but there's no indication that anything happened.

**Comment by reiichi001** [comment]
**Purpose**: Plugin does what it says it's going to do
**Functionality**: Plugin has an issue where the UI does not show up on initial config, but works if the plugin is reloaded. Dev notified and is looking into it.
**Safety**: Plugin adheres to our plugin guidelines. As this is a combat-oriented plugin, there may be additional review by Goat first before it's merged.
**Code Review**: Done by Karashiiro

@goaaats see above before merging.

**Comment by reiichi001** [comment]
Looks good now. Pending Goat approval

**Comment by reiichi001** [comment]
@goaaats / @karashiiro (do we have others who are authorized for official code review), can we refresh the code review for the plugin so we can get this merged?

**Comment by karashiiro** [comment]
I'll re-review this in a minute.

**Comment by karashiiro** [comment]
Code LGTM

**Pull request merged**
