### PR TITLE
Added RaidBuffTracker (updated for 6.05)

### PR DESCRIPTION
**Pull request by shdwp**
image

Adds a widget keeping track of your party actions cooldowns and state, this includes raid buffs, utility and other stuff you might be interested in.

Plugin shows when abilities are active, and where their cooldown is at, helping you to align your burst windows.

### CODE REVIEW

**Comment by nyxalteria** [comment]
isnt this literally job bars

**Comment by shdwp** [comment]
Standby while I will update the opcodes.

**Comment by shdwp** [comment]
Moving it to the `plugins` folder because me and some other people have been testing this extensively for a couple of weeks.

**Comment by shdwp** [comment]
Yeah it's all fine, this can be merged. Pushing it straight to release because me and a few other people were testing it quite extensively for a couple of weeks now.

**Comment by shdwp** [comment]
Fixed for 6.05 and added a few minor things here and there. Good to go. Straight to release since we've been testing it with a couple of people.

**Comment by nyxalteria** [comment]
they aren't merging new combat related plugins, old ones got grandfathered in, you're gonna have to just make this a third party repo

**Comment by reiichi001** [comment]
> they aren't merging new combat related plugins, old ones got grandfathered in, you're gonna have to just make this a third party repo

Not merging new combat-related plugins **right now** pending more discussion on how to determine some guidelines for them.* 

PRs can and should still be made, especially when they can be updated for the current release of Dalamud and aren't otherwise breaking any of the current guidelines.

Devs are free to use custom repos for testing before a plugin's added to the official repo, provided they want to provide support for it elsewhere.

**Comment by shdwp** [comment]
Well you should have came out with an announcement or something. People spent time developing the plugins with current guidelines. It's not like this pushes any boundaries - the same functionality is available as a part of delvui.

**Comment by karashiiro** [comment]
Code LGTM @goaaats

**Pull request closed without merging**
