### PR TITLE
[Testing] CrashFFXIVPlugin

### PR DESCRIPTION
**Pull request by reiichi001**
The latest in bleeding edge Dalamund plogon development by Franz. It brings you exactly what's advertised in the name.

Plugin is respectful and will tag itself for deletion on your next launch. Might require multiple relaunches if cleanup fails unintentionally.

You know exactly what you're asking for when you install this.

PR closed/reopened because I needed to reset my branches and this makes it easier to deal with.

### CODE REVIEW

**Comment by karashiiro** [comment]
Code LGTM

**Comment by karashiiro** [comment]
Besides, like, crashing the game.

**Comment by philpax** [comment]
My opinion on this is that it should not be merged until we have a "funny/joke plugins" section, so until this happens https://github.com/goatcorp/DIPs/issues/4#issuecomment-1127221987

**Comment by philpax** [comment]
Taking an executive decision on this and closing it until we have a new plugin installer

**Pull request closed without merging**
