### PR TITLE
[Testing] A Realm Recorded v0.4.0.0

### PR DESCRIPTION
**Pull request by UnknownX7**
Features improvements to the duty recorder to increase accessibility and overall usefulness. Recording is automatic while inside most duties as long as the following option inside `/record` is enabled.

ffxiv_dx11_2022-05-04_19-07-56

### CODE REVIEW

**Comment by slotthhy** [comment]
While I love the idea, and the plugin works properly (albeit with some erroneous chat messages from the vanilla game thinking you're using the vanilla feature), I think one of the main things we should consider is that the game requires a record ready check from the entire instance in order to record. This plugin does bypass this consent. Whether that matters I would say is not my decision.

**Comment by karashiiro** [comment]
Not sure if it'll cause issues, but one of your image fields is an empty string.

**Comment by UnknownX7** [comment]
> Not sure if it'll cause issues, but one of your image fields is an empty string.

I do this in QoL Bar as well.

**Comment by goaaats** [comment]
Seems like you're still working on this, should we review or wait?

**Comment by UnknownX7** [comment]
I'll push the latest version in a bit. I'm done with almost all of the base features; its mostly just polish remaining for a 1.0.0.0 release.

**Comment by UnknownX7** [comment]
It's ready for review.

**Comment by goaaats** [comment]
Code LGTM, not sure about the recording without check aspect. Personally don't feel like it's a problem, the limitation is pretty artificial anyway and it's a pain in the ass to do record ready checks(I actually think that's why no one uses these in the first place)

If it was a huge issue for someone on the team I guess you could invest in name scrambling or something, but I doubt it. What do you think? @reiichi001 @karashiiro

**Comment by reiichi001** [comment]
The recording consent thing would be tricky IMO. Technically, our rules don't really have anything in place to accommodate that as a requirement.

Does this plugin allow you to record any duty, or only the ones SE currently offers? If the latter, then I'd say it could be looped into the consent there, but if it can record anything, I think we'd want a way to scramble players or default them to a stand-in. Maybe it could be teamed up with Nomina Occulta?

**Comment by Caraxi** [comment]
I personally don't see how its any different to recording other players in a video, consent for that kind of thing seems kinda pointless

**Comment by Aireil** [comment]
It's already hiding the names anyway, you only see job names.

**Comment by karashiiro** [comment]
I don't think it's all that different from OBS or FFLogs, at least inherently. If this was combined with a convenient way to share recordings, there might be a greater problem, but tmk there isn't any such mechanism.

If someone could come up with harms that this could cause that go beyond OBS and FFLogs, then we could consider blocking this without anonymization.

**Comment by karashiiro** [comment]
> It's already hiding the names anyway, you only see job names.

In that case, there shouldn't be any issue.

**Comment by goaaats** [comment]
Could you add an icon?

**Comment by UnknownX7** [comment]
Done.

**Pull request merged**
