### PR TITLE
[Testing] Add Weatherman

### PR DESCRIPTION
**Pull request by Limiana**
Weatherman is an environmental control plugin which allows following:
- Weather change
- Time change
- BGM change (via Orchestrion plugin)

Only visuals are affected.

### CODE REVIEW

**Comment by karashiiro** [comment]
@goaaats Code mostly LGTM, you might want to skim this to determine if it has side-effects, though: https://github.com/Eternita-S/Weatherman/blob/master/Weatherman/MemoryManager.cs

**Comment by karashiiro** [comment]
https://github.com/goatcorp/suggestions/issues/590

**Comment by goaaats** [comment]
Are you up to date with this PR?

**Comment by Limiana** [comment]
Yeah, the uploaded archive is correct

**Comment by goaaats** [comment]
Alright, I'd appreciate if you could change what you have as description into the "Punchline" attribute and write a little more about what the plugin does/features/limitations in "Description". Would be good if you could especially stress that all changes are visual only.

**Comment by Limiana** [comment]
Okay, it's done now

**Pull request merged**
