### PR TITLE
Add ExtraChat 1.2.0

### PR DESCRIPTION
**Pull request by anna-is-cute**
ExtraChat is a plugin that adds unlimited, cross-data-centre, end-to-end-encrypted linkshells to the game.

### CODE REVIEW

**Comment by reiichi001** [comment]
**Purpose**: Plugin does what it says it's going to do.
**Functionality**: Plugin does not appear to have any noticeable issues affecting its core functionality.
**Safety**: Plugin adheres to our plugin guidelines and takes steps to preserve user security. Plugin use is not detectible by non-plugin users.
**Code Review**: Pending review from other team members.

**Comment by reiichi001** [comment]
There are a few thoughts/concerns I have that would have been stuffed into safety if I'd thought about it before posting the previous comment. Things that may need to be addressed to feel comfortable with this on the main repo (and are possibly things other users have brought up elsewhere, but this offers good visibility).

Is there a disclaimer letting users know which data will be stored (and how)? 
-> "ExtraChat will need to cache your player name, world, etc (anything else?) in order to function. These are stored in <x> manner on the server to preserve your private character's information."
-> Do users have a means to "remove all my data" from inside the plugin?

Would it be possible to include a method to disconnect from ExtraChat or to have an "offline mode" that would block a user from trying to just mass-invite everyone on their friendslist to an ExtraChat linkshell?
-> The reasoning here is "what if SE installed this plugin and tried to use it to detect other plugin users?" Are there measures in place to prevent someone from trying to scrape a social list from in-game to see who has this plugin?
-> Is there a measure in place to block invite spam if a user tries to constantly invite the same people over and over? (Compare to getting FC invite spam / unsolicited tells)

**Comment by anna-is-cute** [comment]
> Is there a disclaimer letting users know which data will be stored (and how)?

Yes

> Do users have a means to "remove all my data" from inside the plugin?

No, though their "data" consists of a character name and world linked to nothing else. I could find this by scraping the Lodestone and storing it.

> Would it be possible to include a method to disconnect from ExtraChat or to have an "offline mode" that would block a user from trying to just mass-invite everyone on their friendslist to an ExtraChat linkshell?

No. SE would have a much easier time just changing the binary to detect plugin users; I think this is a non-issue. Users who do not have the plugin installed get the same error as users who are offline. As discussed with Jules, I do not think it's reasonable to implement "fake" invites to prevent enumeration, simply due to how the E2EE works. It would be a massive headache for users and myself.

> Is there a measure in place to block invite spam if a user tries to constantly invite the same people over and over?

No. Just don't accept or decline the invite. Worst case, someone invites, then uninvites, reinvites, and so on. I am most likely not going to add rate limiting to this. I can potentially add something that turns off the toasts, which would be the only annoyance for users.

**Comment by karashiiro** [comment]
Code LGTM

**Comment by anna-is-cute** [comment]
Updated to 1.2.0 which has a delete account button and an option to block invites, which effectively makes you appear to not have the plugin installed.

**Comment by reiichi001** [comment]
@goaaats this should be ready for merge unless you have any additional concerns.

**Pull request merged**
