### PR TITLE
[Testing] XIV Instant Messenger

### PR DESCRIPTION
**Pull request by Limiana**
A direct message manager made in fashion of WoW Instant Messenger.
Key features:
- Open a direct message window when you message someone or they message you
- Each window contains your DM chat with certain person
- Open and cycle through recent chats with a hotkey
- Execute emote commands on a player from their DM window without needing to manually target them
- Automatically record your chat log in an easy to read text file
- Fully customizable styles

### CODE REVIEW

**Comment by karashiiro** [comment]
Please update the zip name to `latest.zip`.

**Comment by NotNite** [comment]
Your folder name and InternalName do not match.

**Comment by karashiiro** [comment]
Code LGTM

**Comment by Limiana** [comment]
Fixed both problems

**Pull request merged**
