### PR TITLE
Add HighFpsPhysicsPlugin to test

### PR DESCRIPTION
**Pull request by Kirrana**
https://github.com/Kirrana/xivlauncher_physics_plugin

### CODE REVIEW

**Comment by karashiiro** [comment]
@goaaats I'm not decoding the injected assembly code here but this one seems super simple if you want to trace it yourself, since it's basically just one (very expanded) function: https://github.com/Kirrana/xivlauncher_physics_plugin/blob/main/SamplePlugin/HighFpsPhysicsPlugin.cs

My bigger concern would be unintended side effects - you're better able to assess that than me.

**Comment by reiichi001** [comment]
Hello! While doing initial testing, this plugin crashed on install/load.

Is it currently updated for FFXIV 6.08 Hotfix? If not, please update the PR with a new release or create a new PR for an updated version and we can re-validate.

**Comment by Kirrana** [comment]
Should be updated for the latest hotfix now, probably

**Comment by reiichi001** [comment]
Please adjust for API 6. You can either close/update this PR. We'll then try to get it through plugin approval.

**Comment by Kirrana** [comment]
Should be rebuilt with the updated packager now.

**Pull request closed without merging**
