### PR TITLE
Add DeathRecap v1.4.0

### PR DESCRIPTION
**Pull request by Kouzukii**
DeathRecap allows you to quickly figure out what killed you!

Shows healing, damage taken, debuffs, buffs, barriers as well as reprisal, addle and feint on target.

deathrecap

Repository: https://github.com/Kouzukii/ffxiv-deathrecap

### CODE REVIEW

**Comment by goaaats** [comment]
Hey! Thanks for your submission, did you test this a lot already? If not, I'd recommend you to move the plugin to the testing folder for now and ask the testers in the Discord to give your plugin a go.
Additionally, it'd be nice if you could add an icon for it(can be mspaint). Much appreciated!

**Comment by Kouzukii** [comment]
Hey, thanks for the quick reply!
I've used this for a while on my local machine, and I've had this available through my third party repository for a while, where people have been using it without issue.
An IconUrl should be attached, unless you want me to add the icon file to the PR as well.

**Comment by Kouzukii** [comment]
I'll add it to testing for now though

**Comment by goaaats** [comment]
If you PR to the main repo, you need to add your icon as /images/icon.png in your plugin folder, to prevent IP leaks. Sorry, should have mentioned.

**Pull request merged**
