### PR TITLE
[Testing] AetherSense Redux 0.7 BETA

### PR DESCRIPTION
**Pull request by digital-pet**
Much like the AetherSense of old, this is a plugin that combines chatlog parsing and the buttplug.io haptic feedback library.

### CODE REVIEW

**Comment by goaaats** [comment]
Hi, we talked about this internally in the team and decided that we shouldn't merge NSFW plugins into the main repo anymore, apologies.
However, feel free to publish your plugin via third party repo. Thank you!

**Comment by digital-pet** [comment]
Understood, thanks!

**Comment by digital-pet** [comment]
Oh, and if anyone else runs into this new policy in the future feel free to point them my way, I'll gladly maintain a central NSFW repo.

**Comment by karashiiro** [comment]
😳

**Pull request closed without merging**
