### PR TITLE
[Testing] Distance 0.9.3.0

### PR DESCRIPTION
**Pull request by PunishedPineapple**
New plugin: [Distance 0.9.3.0](https://github.com/PunishedPineapple/Distance/releases/tag/v0.9.3.0)

Provides one or more widgets that show distance to the target, focus target, etc., and optionally a special widget that shows the distance until aggroing a boss (for supported bosses).

Known issues:
* Missing data for some fights, including p3s, ultimates, normal mode Pandaemonium, and all EW trials.  Feel free to contribute if you want!  (See the plugin repo's readme)

Issues/feedback @ Banana Bread in discord.

### CODE REVIEW

**Comment by karashiiro** [comment]
Code LGTM @goaaats

**Comment by reiichi001** [comment]
**Purpose**: Plugin does what it says it's going to do
**Functionality**: Plugin does not appear to have any glaring issues that aren't otherwise noted by the dev
**Safety**: Plugin adheres to our plugin guidelines

**Comment by reiichi001** [comment]
Please adjust for API 6. You can either close/update this PR.

**Comment by PunishedPineapple** [comment]
Created a new PR (#2253) because I'm too dumb to figure out how to change the target branch for the PR without it getting messy.

**Pull request closed without merging**
