### PR TITLE
[Testing] MimicryHelper 1.0.0.0

### PR DESCRIPTION
**Pull request by RedMage1993**
This plugin makes it easier for the user to use Aetheric Mimicry.

It provides the user with 3 buttons for each type of class role, i.e. Tank, DPS, and Healer.

Upon clicking any of the buttons, the plugin uses ClientState to locate the nearest PlayerCharacter that matches that class role. It then uses ActionManager to automatically attempt using Aetheric Mimicry on that PlayerCharacter.

The user may also perform these actions through the main command (/mimic) by passing an argument specifying the first letter of the role they wish to mimic (i.e. "t", "d", "h"), e.g. /mimic t.

It adds text to the chat log with ChatGui to notify the user that an attempt is being made to use Aetheric Mimicry.

### CODE REVIEW

**Comment by reiichi001** [comment]
This may be considered as automation under our current plugin guidelines as it is inherently making a decision on behalf of the player in order to execute its action. However, the action does require user input in order to do so. 

This plugin may be subject to additional review to make sure it fits within the rules.

**Comment by RedMage1993** [comment]
If necessary, I can probably take the action out so that all it is doing is targeting the player. If that's still automation, I can maybe make it hint the direction the player is at, kind of like the aetherial compass does, and include the name. I guess then it would be more like the Treasure Map finder plugin that brings up the map and flags your treasure's location for you, the pennying plugin that auto copies the lowest price to your clipboard, macro chain, waymark plugin that auto places several makers down, etc. etc.

Would be really cool to keep as is though since, although it could be macro'd, there will hardly ever be any reason to use this in the middle of combat. Typically there'd be only BLU's around, so no healers or tank to mimic. You'd normally want a player to take a specific set of spells, that enable an opener or rotation meant for that role, and you cannot change your set of spells in the middle of combat. Bringing in multiple spells meant for different roles would likely always be wasteful.

It would really enhance the BLU experience more than automate anything. Typically when you want to do anything on BLU you might as well mimicry. Problem with it is how you have to look around for someone to mimic which can be a pain as it is kind of RNG and unnecessary but is something that typically all members of a BLU party must/should do anyway. All it does is slow people down, pressures player to teleport to crowded area where they may have a chance to find the right role. But as mentioned, this plugin can technically solve that problem without actually targeting or running mimicry. Those things would just really be nice to have/keep since it makes it more like what I and probably others wish mimicry would be--just a stance button like tanks have or how red mage can switch between white/black buffs in PvP, etc.

**Comment by Helios747** [comment]
Repeating what I said here

intent with automation is important to consider. For Mimicry helper, it's harmless automation. When you join a PF to farm something with BLU people want specific mimicries. you sort this out outside of the duty. You can't do it in duty.

If we're reeeaally wanting to take a 1 input = 1 output stance on all of our plugins, we'll need to re-assess several plugins, all of which again, have intentions of not trying to maliciously automate anything.

**Comment by goaaats** [comment]
Yeah, I think this is fine, after reading through what was said here. Will look at merging later.

**Comment by karashiiro** [comment]
Sorry for the extreme delay on reviewing this, we're revising our plugin approval process right now to avoid this in the future. I believe goat will be looking at this soon (code LGTM).

**Comment by RedMage1993** [comment]
No problem. Thank you for the update and review :)

**Pull request merged**
