### PR TITLE
Update KingdomHeartsPlugin to 1.0.5.0.

### PR DESCRIPTION
**Pull request by Arrenton**
Changes:
- Removed sound features and moved to independent plugin.
- Added error messages for portrait images

### CODE REVIEW

**Comment by reiichi001** [comment]
@goaaats, since this is splitting functionality into two plugins, do we need to go through code review again? This PR also has them grouped together. Should we have that split?

**Comment by Arrenton** [comment]
Apologies if this is an issue. I have few experience with PRs and was going to make multiple, but it recognized both commits so I just left it and edited the PR.

**Comment by karashiiro** [comment]
They should probably be split just so that franzbot posts them separately, but that's just my opinion.

**Comment by Arrenton** [comment]
If it will help, I can revert the commit I made that added the new plugin then make a new PR for the new plugin.

**Comment by reiichi001** [comment]
> If it will help, I can revert the commit I made that added the new plugin then make a new PR for the new plugin.

I'd separate them out so we can merge KH immediately and then get review done on the audio plugin.

**Comment by Arrenton** [comment]
Done. Changed the title and comment as well.

**Pull request merged**
