### PR TITLE
[Testing] Added venue management plugin to testing

### PR DESCRIPTION
**Pull request by FatigueDev**
Note: This accesses an always-on web API hosted at https://venyou.gigalixirapp.com

### CODE REVIEW

**Comment by karashiiro** [comment]
Code LGTM

**Comment by FatigueDev** [comment]
Changelog for 47b744a:
* Added notification widget.
* Increased general stability.
* Set refresh timer to 30 seconds to ease load on servers. (Used to be like 3 seconds- Yikes!)

**Comment by goaaats** [comment]
Hey, could you add an icon? Looks good otherwise, thanks!

> An icon for your plugin has to be in "YourPlugin/images/" as "icon.png". The icon has to be representative of what your plugin does, ideally have transparency and be at max, 512 by 512 pixels.

**Comment by FatigueDev** [comment]
Ready to merge, don't have any large changes of note without the data migration I'm working on in the DB to add datacenter / world filtering.

**Comment by slotthhy** [comment]
Hi! Apologies for the delay. I've noticed a few issues with the plugin so far. It seems like your zip file contains some unused files - those should be removed. I recommend @goatcorp/DalamudPackager to create the release zip file. This will be required in the future in the new build system, anyways. This should be fixed before merging.

For the plugin itself, it seems to break when opening more than one venue at a time - the description for other venues will appear in previous venues' description boxes. Your settings window is also blank - if you don't have any settings, you don't need a settings window. These should be fixed before merging.

I had some minor gripes personally with the usability with regards to the absence of text wrapping for venue descriptions, editable text boxes (?) for venue information, and the length of time it takes for the initial load. While these have nothing to do with whether the plugin will be merged, seeing improvements here would be great.

**Comment by FatigueDev** [comment]
Hey @lmcintyre , I'm currently working on a whole database migration and the plugin has sort of fallen to the wayside while that happens. If I close this pull request, I plan to just remake it from scratch to be 'view only'- Editable only from the site I'm hosting. I'd like to give them the control to create venues from in the plugin but my C# isn't the best and it's pretty tricky! Fun, but tricky. I'll take what I've learned and your advice for repackaging and re-issue one if I'm comfortable with the results of the database migration and website revamp- Thank you so much for letting me know and I'll be sure to take the advice on board with the next round.

No idea how long the migration will take, but it's well underway :)

**Pull request closed without merging**
