### PR TITLE
Neko Fans

### PR DESCRIPTION
**Pull request by Meisterlala**
This is a new plugin, which simply shows you a random image of a cat girl. 
It is inspired by the popular Beat Saber mod [Nya](https://github.com/Sirspam/Nya)

The images are pulled async from the [nekos.life](https://nekos.life) api and should be SFW.

You can also test this plugin by using this custom plugin repository
```
https://raw.githubusercontent.com/Meisterlala/NekoLife/master/repo.json
```
You can find the source code in my [git repository](https://github.com/Meisterlala/NekoLife)

If there is interest in this plugin, then i will add a configuration menu where you can choose different types of pictures from different websites. Feedback is appreciated.

### CODE REVIEW

**Comment by philpax** [comment]
Hey there! Neat plugin, but there's a couple of things we'd like you to address before we merge it in:

1) We've tested the API endpoint, and it's unfortunately not as consistently SFW as one would hope. Can you add a note to the description that the images might be risque/NSFW so that people know what to expect?
2) The configuration doesn't contain anything, so an empty entry will be saved. Not a big deal, but can you add something to the config, remove the config entirely (should work fine without it), or let us know if you're planning to add to it in the future (and if so, we'll wave it through)?
3) [This line](https://github.com/Meisterlala/NekoLife/blob/master/Neko/Plugin.cs#L49) unsubscribes from the config command handler, but the initial subscription never happens, which might result in errors on unload. You can comment this line out too, or wire up the config command handler. Your call.

Otherwise, looks good 🐈 

(I've also been told to suggest support for https://shibe.online/ so that everyone can get a dose of happiness, but I leave that up to you to consider 😄)

**Comment by Meisterlala** [comment]
Thank you for the fast review.

I have modified the description of the plugin to indicate that there might be NSFW images.
I have also commented out all lines, which have to do with the configuration and fixed the unused command.
Here is the [commit](https://github.com/Meisterlala/NekoLife/commit/caa94c90ef229d22ca11f30abe566c786f2549a4)

When i get around to implementing a configuration menu, I will be sure to add shibe as an option 😉

**Comment by Caraxi** [comment]
Another issue I've just noticed
- The plugin name in the Json is "Neko Fans" while all other references to the name call it "Neko Life"

**Comment by Meisterlala** [comment]
When I started development i choose the name "Neko Life" but then decieded to change it to "Neko Fans" to avoid confusion with the website [nekos.life](https://nekos.life/).
I have now removed the name "Neko Life" (hopefully) everywhere.

**Comment by philpax** [comment]
Congratulations on your first plugin! 🙂

**Pull request merged**
