### PR TITLE
[Testing] MBHistory

### PR DESCRIPTION
**Pull request by Infiziert90**
A plugin that simply copies the marketboard transaction history into the users clipboard, with customizable options of what will be copied, chatlog options alongside a simple viewing window of what the current selection is.

### CODE REVIEW

**Comment by reiichi001** [comment]
**Purpose**: Plugin does what it says it's going to do
**Functionality**: Plugin does not appear to have any glaring issues that aren't otherwise noted by the dev
**Safety**: Plugin adheres to our plugin guidelines
**Code Review**: Pending review from other team members.

Additional notes: Technically conflicts with other plugins that copy to clipboard, like PennyPincher. It may help to add a "recopy last seen entry" button or command, or to pop a warning if a conflicting plugin is loaded.

**Comment by goaaats** [comment]
Please add an icon to this.

**Comment by Infiziert90** [comment]
added an icon

**Comment by Aireil** [comment]
Unless that changed, `IconUrl` is only used for 3rd party plugins, you have to add `icon.png` in `MBHistory/images`

**Pull request merged**
