### PR TITLE
Create .gitattributes

### PR DESCRIPTION
**Pull request by lokinmodar**
Please allow for LFS support. I'm having trouble with all the fonts and translation resources for the multiple languages supported <3

### CODE REVIEW

**Comment by goaaats** [comment]
How big is the plugin you want to upload?

**Comment by lokinmodar** [comment]
100+ MB due to localization stuff + fonts per script

**Comment by goaaats** [comment]
What stuff exactly?
I'd probably prefer if you could download this stuff at runtime as dependency, just like BrowserHost does it. This would prevent people having to redownload 100+ MB of largely unchanged stuff just for a small code change when the plugin updates as well.

**Comment by lokinmodar** [comment]
The stuff is compiled as separate dll resources by language when VS builds the project by the Multilingual App Toolkit...

**Comment by ackwell** [comment]
https://github.com/ackwell/BrowserHost/blob/master/BrowserHost.Plugin/DependencyManager.cs code for what goat mentioned in BH.

iuno localisation in .net but you might even be able to set up diff. deps per language and optionally download only the resources for the languages the user is interested in.

**Comment by lokinmodar** [comment]
Closing this as I will come up with a different solution. Meanwhile i'm disabling some languages to reduce update size.

**Pull request closed without merging**
