### PR TITLE
[Testing] Target Furniture 1.0.1.2

### PR DESCRIPTION
**Pull request by InitialDet**
Currently, the only possible way to select a housing item is to click it manually with your mouse over it, and that can be a problem if you have multiple items close to each other. 

This plugin adds a new option when right-clicking an item from the Housing Menu, targeting the item and saving you a lot of trouble.

<p></p>

### CODE REVIEW

**Comment by reiichi001** [comment]
**Purpose**: Plugin does what it says it's going to do
**Functionality**: Plugin does not appear to have any glaring issues. See notes below.
**Safety**: Plugin adheres to our plugin guidelines
**Code Review**: Pending review from other team members.

Additional notes: I'd add a warning that the alternative targeting mode can result in moving an item and making it disappear. (Or this is what I experienced during reviewing it. ...had to take a few moments to realize that the item I targets was nowhere to be seen as it immediate went into placement mode.)

**Comment by InitialDet** [comment]
I'm not sure I understood what happened when you tried the alternative version. Could you share a screenshot/video with me if possible?

**Comment by InitialDet** [comment]
https://user-images.githubusercontent.com/13919114/168454942-c96e7aa0-36d4-4b10-ae19-2135a7cfb9bc.mp4

They have similar functions based on my tests.

**Comment by reiichi001** [comment]
Originally when I tested the default mode, target only targeted, but alt immediate set the item to my move cursor. 

Testing indoors, they look to be the same, although when I tested in my FC's outside area, I had a bit of an issue where pressing escape did not reset the item back to where it was, but instead made it disappear. (Could not reproduce in FC room). This could entirely be user error though, as I'm not able to re-reproduce it.

All looks to be working as expected. (Entirely possible that something wonky happened when loading all the plugins I was planning to review)

**Comment by InitialDet** [comment]
Ah, I understand. I'm currently trying to reproduce this situation outside/inside my FC house, but nothing out of the normal seems to happen for me at least.

**Comment by reiichi001** [comment]
> Ah, I understand. I'm currently trying to reproduce this situation outside/inside my FC house, but nothing out of the normal seems to happen for me at least.

I tried to reproduce it outside on another character, but couldn't, so I think you're good! Once someone else can do code review, this should be ready to merge.

**Comment by InitialDet** [comment]
https://user-images.githubusercontent.com/13919114/168456778-f744716f-77e5-49ce-a83c-ddb3ab60e81a.mp4

While looking at the code I decided to add an option that makes the furniture follow/not follow the cursor while using the default mode. Some users might prefer this. I also tried to enhance the warnings message in the alternative option.

**Comment by karashiiro** [comment]
Sorry for the extreme delay on reviewing this, we're revising our plugin approval process right now to avoid this in the future.

**Comment by karashiiro** [comment]
Code LGTM, can you add an icon, please?

**Comment by InitialDet** [comment]
It should have an icon already

**Comment by NotNite** [comment]
You need to put it in `images/icon.png`.

**Comment by InitialDet** [comment]
> You need to put it in `images/icon.png`.

https://github.com/InitialDet/TargetFurniture/tree/main/TargetFurniture/images

It does have an icon, unless im missing something else?

**Comment by NotNite** [comment]
Sorry, should have clarified - in this repo, `testing/TargetFurniture/images/icon.png`.

**Comment by reiichi001** [comment]
> https://github.com/InitialDet/TargetFurniture/tree/main/TargetFurniture/images
> It does have an icon, unless im missing something else?

That's over in the plugin source, but it's not in this PR. (The images folder is part of the DalamudPlugins structure)

So the PR should have:
- latest.zip
- plugin manifest (the json file)
- Images folder (naming is strict and it has to be icon.png etc)

**Comment by InitialDet** [comment]
It should be good now

**Comment by reiichi001** [comment]
Please ping me (Unnamed Mercenary#1846) in Goatplace for the plugin creator role if you'd like it.

**Pull request merged**
