### PR TITLE
[Testing] StackSellPrice

### PR DESCRIPTION
**Pull request by VariableVixen**
Just puts the total sell price for a stack of items on the tooltip for it when hovering.

Only accounts for the number of items in the stack being hovered over, and doesn't apply to unsellable items.

Full code is [here on github](https://github.com/PrincessRTFM/StackSellPrice) for review.

### CODE REVIEW

**Comment by karashiiro** [comment]
Sorry for the delay, I've been busy ><

Code LGTM, but can you add an icon to this, please?

**Comment by VariableVixen** [comment]
All good, the only problem is that I don't _have_ an icon for it. I'm open to suggestions if anyone has any, but I've never been any good at design or anything like that.

**Comment by karashiiro** [comment]
https://github.com/xivapi/classjob-icons this repository has some icons to work with, maybe something based on [this](https://github.com/xivapi/classjob-icons/blob/master/svg/Gil.svg)?

**Comment by karashiiro** [comment]
Rasterizing it and using it as-is is probably fine, even.

**Comment by VariableVixen** [comment]
Alrighty, [icon added](https://raw.githubusercontent.com/PrincessRTFM/StackSellPrice/master/icon.png). I just inverted the colour so it won't be black-on-black in the installer window. Firefox doesn't seem to want to render it right, I promise the background _is_ transparent, and I re-downloaded it to verify.

**Comment by karashiiro** [comment]
Oh, for main repo plugins, the icon needs to be on this repo itself, at `images/icon.png`. Besides that, looks good, if @reiichi001 @goaaats want to do their passes.

**Comment by VariableVixen** [comment]
Oh, gotcha. Gimme a sec...

**Comment by reiichi001** [comment]
**Purpose**: Plugin does what it says it's going to do
**Functionality**: Plugin works and there are no noticeable issues.
**Safety**: Plugin adheres to our plugin guidelines

**Comment by reiichi001** [comment]
Please ping me (Unnamed Mercenary#1846) in Goatplace for the plugin creator role if you'd like it.

**Pull request merged**
