### PR TITLE
SonarPlugin v0.1.1.0

### PR DESCRIPTION
**Pull request by rreminy**

### CODE REVIEW

**Comment by goaaats** [comment]
Hey! Please +1 the API level of your plugin json, both inside the ZIP and in the PR.

**Comment by goaaats** [comment]
If you use Lumina, please make sure to link against the staging build of Dalamud which you can get by ticking the experimental builds option in /xlsettings.

**Comment by rreminy** [comment]
will the experimental version Lumina work with the current version present in the stable version of Dalamud?

**Comment by goaaats** [comment]
It will become stable with 5.4 release

**Comment by rreminy** [comment]
alright, updated

**Pull request merged**
