### PR TITLE
[Testing] Add KikoGuide

### PR DESCRIPTION
**Pull request by Blooym**
## Information
Adds guides on how to clear duty finder content, with spoiler protections.

Repository URL: https://github.com/BitsOfAByte/KikoGuide

## Preview 
image
Red indicates a duty that is yet to have data on the KikoGuide repository. Duties that are not unlocked are not shown anywhere in the UI

### CODE REVIEW

**Comment by slotthhy** [comment]
It looks like you're not utilizing client structs in your plugin but you're shipping the DLL (copied from the Dalamud folder) and initializing the resolver. This may cause issues. You have to remove the Initialize and I'd recommend not including the DLL in your plugin zip unless you require a more updated client structs than Dalamud has available to you in the dev folder. Other than that, code and functionality looks good to me @goaaats.

**Comment by Blooym** [comment]
I believe I have made the correct changes as requested 👍

**Comment by Blooym** [comment]
Changelog from v1.0.2.0 (initial submit) to v1.0.4.0:
https://github.com/BitsOfAByte/KikoGuide/compare/v1.0.2.0...v1.0.4.0

No major Plugin code changes, just some window dimension changes, duty file updates & optimisations.

**Comment by philpax** [comment]
Congratulations on submitting your plugin! Looking forward to seeing how you go 🙂

**Comment by philpax** [comment]
If you're on the Goat Place Discord, ping us in #plugin-dev and we'll give you access to the dev-specific channels

**Pull request merged**
