### PR TITLE
PlayerTags v1.3

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Changelog for Version 1.3
- Reimplemented the Context Menu feature
- Polished up some code for Context Menu feature

Changelog for Version 1.2
- Updated for API v6
- Disabled context menus for now (will be re-added soon with a future update)
- Updated the plugin info
- Minor improvements

### CODE REVIEW

**Comment by NotNite** [comment]
Worth noting that the old maintainer of PlayerTags has given Pilzinsel64 permission to maintain a fork - see [here](https://github.com/r00telement/PlayerTags/pull/10#issuecomment-1156367184).

**Comment by MidoriKami** [comment]
You don't need to include changelog information in the .json
It is generated automatically from the text in this pull request

Additionally the iconurl field in the .json is not used

**Comment by NotNite** [comment]
Also, worth adding, you might want to preserve the original author's name in the metadata. If you do apply these changes, make sure to edit the JSON in the .zip file, too!

**Comment by Pilzinsel64** [comment]
Oh, ok, good to know. I'm sorry. I fixed your points.

**Comment by NotNite** [comment]
No need to be sorry! You can actually remove the Changelog/IconUrl fields if you want, instead of blanking them out. Also, now that I've thought about it (lol, sorry), you might want to set the author to `r00telement, Pilzinsel64` so you can keep credit.

**Comment by Pilzinsel64** [comment]
Ah, alright. make sense!
Pushed an another commit. 😄

**Comment by MidoriKami** [comment]
Sorry for piling on... haha, Finally took a proper look at things.
I believe the imageurl tag is also ignored.

icons are loaded from `/PlayerTags/images/icon.png`
images are loaded from `/PlayerTags/images/image1.png` and `/PlayerTags/images/image2.png`

Please see (https://github.com/goatcorp/DalamudPlugins/tree/api6/plugins/BigPlayerDebuffs) as an example of where the images need to be and how they need to be formatted.

New rules require plugins to have an icon, please update the PR to include the images folder ^_^

**Comment by Pilzinsel64** [comment]
Oh alright. That's ok, somewhen it needs to be polished to follow the current rules. :D

New commit pushed with images folder and without ImageUrls property.
The images and the icon showed up for me when installed as dev plugin. Didn't think about that.

But sure to remove that property? Will Dalamud automatically detect the correct images at /testing/PlayerTags/images or /PlayerTags/images in all cases? Just asking to get sure it's not needed in the PlayerTags.json since in BigPlayerDebuffs.json there is also a ImageUrls and IconUrl property.

Edit: sorry for the wrong commit name again. Whenever I want to write v1.2 I write v1.12 first. Probably because I do that for another program often

**Comment by MidoriKami** [comment]
DevPlugins work a bit differently. I myself had trouble previewing icon stuff when I was first working on my plugins. Once the plugin is PR'd into the repo it uses the images directly from the images folder.

Big Player Debuffs was simply the first plugin I saw that had an `image1.png`, there are several plugins that still have the iconurl and imageurl attributes. I am trying to save you from wasting time pointlessly updating the urls in those tags when you decide to change things.

If you look through the repository you will find other plugins that have the images in the folders but don't have the attributes in the json, the first in the list alphabetically I saw was ChatBubbles. I'm not going to spend any more time looking for more examples to prove what I already told you.
(https://github.com/goatcorp/DalamudPlugins/tree/api6/plugins/ChatBubbles)

Your Pull Request, Looks Good To Me now.

**Comment by Pilzinsel64** [comment]
Hey, I just pushed v1.3 with re-implemented Context Menu integration. Can I leave it here or should I open a new pull request for?

**Comment by Pilzinsel64** [comment]
Hey. V1.3 seems to be very stable to me as It was before my changes (v1.1.6.1). That's why I moved it out of testing.
So, let's give people the long-awaited update for this Plugin. :)

Also, do I have to do anything else here to get this merged? Or is that done by hand and I don't need to to anything?
Sorry for asking, but it's the first time for me. :D

**Comment by reiichi001** [comment]
Code changes from later commits look fine to me. Will pass along to @goaaats for review because new dev.

**Comment by goaaats** [comment]
Thanks, sorry for the wait

**Pull request merged**
