### PR TITLE
[Testing] InventorySearchBar

### PR DESCRIPTION
**Pull request by Tischel**
Simple plugin that adds a search bar to the inventory window to filter items.

Repo: https://github.com/Tischel/InventorySearchBar

Preview: [Usage example](https://github.com/Tischel/InventorySearchBar/blob/master/Images/example_1.gif)

image

Note: This plugin uses a library made by @Critical-Impact (creator of Inventory Tools).
I talked with them and got their permission to use it for this plugin.

### CODE REVIEW

**Comment by slotthhy** [comment]
Can you change the punchline to something more descriptive?

**Comment by Tischel** [comment]
> Can you change the punchline to something more descriptive?

Oh, totally forgot about that. I'll think about something.

**Comment by Tischel** [comment]
Should be presentable now :)

**Comment by philpax** [comment]
🚀

**Pull request merged**
